name: kafka-forwarder

services:
  kafka:
    hostname: broker
    container_name: broker
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    env_file:
      .env

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - "5000:5432" # Port conflict??? Spring doesn't connect when port is set to 5432 (wslrelay.exe is stealing port 5432 on localhost (!) )
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d brokerdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: