name: kafka-forwarder

services:
  kafka:
    hostname: broker
    container_name: broker
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    env_file:
      .env

  # PostgreSQL Database (use with spring.profiles.active=postgres)
  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - "5001:5432" # Port conflict??? Spring doesn't connect when port is set to 5432 (wslrelay.exe is stealing port 5432 on localhost (!) )
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d brokerdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # H2 Database (use with spring.profiles.active=h2)
  h2:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - "8083:81"    # H2 web console (internal port 81 -> external 8083)
      - "9093:1521"  # H2 TCP server (internal port 1521 -> external 9093)
    volumes:
      - h2_data:/opt/h2-data
    environment:
      H2_OPTIONS: "-ifNotExists -tcpAllowOthers -webAllowOthers"


  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.5.0
    container_name: network_simulator
    ports:
      - "28474:8474" # Control API
      - "28081:28081" # Proxy for Server
      - "28082:28082" # Proxy for Client
    volumes:
      # Mount the config file into the container
      - ./toxiproxy.json:/config/toxiproxy.json
    # Tell Toxiproxy to load the config file
    command: -config /config/toxiproxy.json -host 0.0.0.0
    extra_hosts:
      # Required for container to see your localhost apps
      - "host.docker.internal:host-gateway"

    profiles: ["chaos"]

  toxiproxy-configurator:
    image: curlimages/curl
    depends_on:
      - toxiproxy
    volumes:
      - ./toxics.json:/toxics.json
    command: >
      /bin/sh -c "
      echo '--- DEBUG START ---';
      while ! curl -s http://toxiproxy:8474/version > /dev/null; do echo 'Waiting for Toxiproxy...'; sleep 1; done;
      echo '--- TOXIPROXY READY ---';
      echo '--- INJECTING CHAOS ---';
      curl -v -X POST -H 'Content-Type: application/json' -d @/toxics.json http://toxiproxy:8474/proxies/server_proxy/toxics;
      curl -v -X POST -H 'Content-Type: application/json' -d @/toxics.json http://toxiproxy:8474/proxies/client_proxy/toxics;
      echo '--- DONE ---';
      "

    profiles: ["chaos"]

volumes:
  postgres_data:
  h2_data:
