spring.application.name=http-forwarder

# Kafka config
kafka.bootstrap=localhost:9092
kafka.topics=topic1,topic2

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
## PostgreSQL (Doesn't work if docker container is on default port 5432 ???)
# (wslrelay.exe is stealing port 5432 on localhost (!) )
spring.datasource.url=jdbc:postgresql://localhost:5000/brokerdb
spring.datasource.username=test
spring.datasource.password=test
# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=create-drop
